steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west2-docker.pkg.dev/smart-athlete-448009-i6/mlopsproj/train:latest',
    '-f',
    './dockerfiles/train.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west2-docker.pkg.dev/smart-athlete-448009-i6/mlopsproj/train:latest'
  ]
options:
  logging: CLOUD_LOGGING_ONLY