# configs/config.yaml

# Random seed for reproducibility
seed: 42

# Model configuration
model:
  model_name: "albert/albert-base-v2" # types: "albert-base-v2"
  dropout: 0.3
  num_classes: 2

# Optimizer configuration
optimizer:
  type: "adam" # can be "adam", "adamw", or "sgd"
  lr: 2e-5

# Data configuration
data:
  max_length: 512 # Currently unused
  test_size: 0.2 # Currently unused
  path: "data/processed/train_drcat_04.csv" # Path to processed data

# Training configuration
training:
  output_dir: "models"
  batch_size: 16
  max_epochs: 10
  precision: "16-mixed"  # Currently unused # for mixed precision training
  num_workers: 8

  # Callbacks
  save_checkpoints: false
  save_top_k: 3
  early_stopping: true
  patience: 3 # Early stopping patience

# Logging configuration
logging:
  use_wandb: false  # Set to true to enable Weights & Biases logging
  project_name: "text-detect"
  run_name: "test-run"