# configs/config.yaml
hydra:
  job:
    chdir: false

# Random seed for reproducibility
seed: 42

# Model configuration
model:
  model_name: "prajjwal1/bert-tiny" # types: "albert-base-v2", "prajjwal1/bert-tiny"
  dropout: 0.3
  num_classes: 2

# Optimizer configuration
optimizer:
  type: "adamw" # can be "adam", "adamw", or "sgd"
  lr: 2e-5

# Data configuration
data:
  num_workers: 8
  max_length: 512
  test_size: 0.2 # Currently unused
  path: "data/processed/train_drcat_04.csv" # Path to processed data

# Training configuration
training:
  save_model: True
  output_dir: "models"
  model_name: model.pth
  num_workers: 8
  batch_size: 16
  max_epochs: 2
  precision: "16-mixed"
  # Callbacks
  save_checkpoints: False
  save_top_k: 3
  early_stopping: True
  patience: 3 # Early stopping patience

# Logging configuration
wandb:
  use_wandb: True  # Set to True to enable Weights & Biases logging
  save_artifact: True 
  project_name: "text-detect"
  run_name: "test-run"
