# configs/config.yaml

# Random seed for reproducibility
seed: 42

# Model configuration
model:
  model_name: "roberta-base"
  dropout: 0.3
  num_classes: 2

# Optimizer configuration
optimizer:
  type: "adam" # can be "adam", "adamw", or "sgd"
  lr: 2e-5

# Data configuration
data:
  max_length: 512 # Currently unused
  test_size: 0.2 # Currently unused

# Training configuration
training:
  batch_size: 16 # Currently unused
  max_epochs: 10 # Currently unused
  precision: "16-mixed"  # Currently unused # for mixed precision training
  # num_workers: 4 # Currently unused
  # output_dir: "outputs" # Currently unused
  save_top_k: 3 # Currently unused
  early_stopping: true # Currently unused
  patience: 3 # Currently unused
  accelerator: "auto"  # "cpu", "gpu", "auto" # Currently unused
  devices: 1 # Currently unused

# Logging configuration
logging:
  use_wandb: false  # Set to true to enable Weights & Biases logging
  project_name: "text-detect"
  run_name: "roberta-base-run"