# configs/default.yaml
defaults:
  - model: bert_tiny
  - optimizer: adamw
  - data: default
  - training: default

logging:
  enable_wandb: True # Set to True to enable Weights & Biases logging and saving
  artifact_name: "llm-detector-model" # Name of the artifact which all models are saved to
  # Loggable metrics
  precision: True
  recall: False
  f1: False
  auroc: False

seed: 42 # Random seed for reproducibility

hydra:
  job:
    chdir: false # Stops hydra from changing the CWD
