name: API integration tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    env:
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      PYTORCH_MPS_HIGH_WATERMARK_RATIO: 0.8  # Set memory limit for MPS
    strategy:
      matrix:
        operating-system: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -r requirements.txt
          pip install -r requirements_dev.txt
          pip install -e .
          pip list

      - name: Run API integration tests
        run: |
          pytest src/tests/integrationtests/test_apis.py -v --capture=no
